spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:~/test/DB_CLOSE_DELAY=10;AUTO_RECONNECT=TRUE;
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
      hibernate.generate_statistics: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
